name: nightly-build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Daily “At 00:00”

jobs:
  build:
    if: ${{ github.repository_owner == 'ProjectPythia' }}
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      build_command: 'myst build --html'  # Remove --execute flag to respect myst.yml config

  deploy:
    needs: build
    uses: ProjectPythia/cookbook-actions/.github/workflows/deploy-book.yaml@main


  link-check:
    if: ${{ github.repository_owner == 'ProjectPythia' }}
    uses: ProjectPythia/cookbook-actions/.github/workflows/link-checker.yaml@main
